name: Rewards Auto Run

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
          python main.py
